### ISSUE TITLE
[Question] 'Padding' in send message

### ISSUE THREAD

**Issue by majidmc2** [painor/telethon-secret-chat#10]
I want to see **Padding** when I send/receive a text message. At first I edited this [line](https://github.com/painor/telethon-secret-chat/blob/7aa0c9a3b0fa5b3288a6107958b0908b2f35814c/telethon_secret_chat/secret_methods.py#L401):
`padding_data = os.urandom(padding)`
`print("padding data: ", padding_data)`
`message += padding_data`
`print("+ message: ", message)`

Then I print the decrypted data after this [line](https://github.com/painor/telethon-secret-chat/blob/7aa0c9a3b0fa5b3288a6107958b0908b2f35814c/telethon_secret_chat/secret_methods.py#L588)
`print("decrypted data:", decrypted_data)`

I used two client for test but  **message!=decrypted_data** and I can't see the padding on **decrypted_data** ! This is depends on protocol design (MTProto 2.0, part 2) or I am mistake in read 'decrypted_data' or 'padding'?

**Comment by painor** [comment]
why would you want to do that ? to save data in it ? I don't think telegram will allow that;

**Comment by majidmc2** [comment]
Yes @painor, I research on strengths and weaknesses of MTProto 2.0. I read [this](https://telegram.org/privacy#3-3-2-secret-chats) and I think telegram doesn't validate the payload.

**Comment by painor** [comment]
well yeah they don't actually validate anything and your client is both the server and client depending on who started the chat.
So you can send custom objects if the other party understands them but most official clients won't.

I remember when I was writing the code I would use static values not random and I would verify them when received so I think it's possible.

**Comment by majidmc2** [comment]
Could you please help me which function I should overwrite for this purpose (send/receive a custom objects in custom client)?

**Comment by majidmc2** [comment]
> Could you please help me which function I should overwrite for this purpose (send/receive a custom objects in custom client)?

**Comment by majidmc2** [comment]
> Could you please help me which function I should overwrite for this purpose (send/receive a custom objects in custom client)?

@painor

**Comment by painor** [comment]
Are you sure you're not seeing it there ? message_data_length should have the actual length while decrypted_data should have the ecnrypted+padding so to get the padding you'll need to do something like decrypted_data[message_data_length:]

**Comment by painor** [comment]
in any case if you want to talk more about this you can use the official telethon telegram group or it's offtopic group .

**Comment by majidmc2** [comment]
Thanks for your help.

> Are you sure you're not seeing it there ? message_data_length should have the actual length while decrypted_data should have the ecnrypted+padding so to get the padding you'll need to do something like decrypted_data[message_data_length:]
