### ISSUE TITLE
Secret text messages don`t sent

### ISSUE THREAD

**Issue by mivendors2020** [painor/telethon-secret-chat#2]
When I use replier I can only decrypt message so just read incoming messages 
If I want reply or respond on event nothing is happened in chat

**Comment by rnyPlanet** [comment]
@painor, is there a working example of sending SMS? when i try to send SMS to secret chat it doesn't send (

**Comment by painor** [comment]
what device are you using ? and what do you mean by SMS ?

**Comment by rnyPlanet** [comment]
telegram android. sms = message

**Comment by drizzt** [comment]
I confirm it doesn't work (event.reply) if you use sqlite as storage

**Comment by painor** [comment]
since it's working fine on my machine I think the best thing to do is to send full debug logs+code/device used to either the telethon chat or the offtopic one so I can take a better look at it.

**Comment by rnyPlanet** [comment]
> since it's working fine on my machine I think the best thing to do is to send full debug logs+code/device used to either the telethon chat or the offtopic one so I can take a better look at it.

how can I show the logs?

and there was an error here https://github.com/painor/telethon-secret-chat/blob/master/telethon_secret_chat/secret_methods.py#L89

As far as I understand, it is True here and saves to a temporary chat
https://github.com/painor/telethon-secret-chat/blob/master/telethon_secret_chat/secret_methods.py#L136

**Comment by ghost** [comment]
@painor, after create secret chat, when i try send message and use id secret chat - from ```value=await manager.start_secret_chat("@chatname")``` i get id, but when try send message by this id parametrs in ``` await manager.send_secret_message(peer_id=value,message="hello friend")``` i get error -   r**aise ValueError("chat not found")
ValueError: chat not found**

**Comment by rnyPlanet** [comment]
> @painor, after create secret chat, when i try send message and use id secret chat - from `value=await manager.start_secret_chat("@chatname")` i get id, but when try send message by this id parametrs in ` await manager.send_secret_message(peer_id=value,message="hello friend")` i get error - r**aise ValueError("chat not found") ValueError: chat not found**

As far as I understand, it is True here and saves to a temporary chat
https://github.com/painor/telethon-secret-chat/blob/master/telethon_secret_chat/secret_methods.py#L136
you need to put False and then it will find the chat. but message will not send

**Comment by ghost** [comment]
> > @painor, after create secret chat, when i try send message and use id secret chat - from `value=await manager.start_secret_chat("@chatname")` i get id, but when try send message by this id parametrs in ` await manager.send_secret_message(peer_id=value,message="hello friend")` i get error - r**aise ValueError("chat not found") ValueError: chat not found**
> 
> As far as I understand, it is True here and saves to a temporary chat
> https://github.com/painor/telethon-secret-chat/blob/master/telethon_secret_chat/secret_methods.py#L136
> you need to put False and then it will find the chat. but message will not send

And why message not send?

**Comment by rnyPlanet** [comment]
but why I don't know. maybe something with a telegram. it creates a chat but doesn't send (

**Comment by painor** [comment]
would be better to create a separate issue or maybe try asking in the group if the question is too specific. also what telegam client exactly ? tg x ?

**Comment by erridius** [comment]
> ‎было бы лучше создать отдельный вопрос или, может быть, попытаться задать в группе, если вопрос слишком специфичен. Кроме того, что телегамы клиента точно? tg x?‎

Original telegram client on android.

**Comment by ghost** [comment]
> would be better to create a separate issue or maybe try asking in the group if the question is too specific. also what telegam client exactly ? tg x ?

Original telegram client on android.
