### ISSUE TITLE
ValueError: chat not found

### ISSUE THREAD

**Issue by d2nekomet** [painor/telethon-secret-chat#8]
My code:
from telethon import TelegramClient
from telethon_secret_chat import *

client = TelegramClient(session='session_name', api_id=1,
							api_hash='hash')

async def main():
	chat = await manager.start_secret_chat('my_username')
	print(chat)
	await manager.send_secret_message(chat, 'Hi')

manager = SecretChatManager(client, auto_accept=False)

with client:
	client.loop.run_until_complete(main())

**Comment by painor** [comment]
When you start a secret chat you need to wait for the other party to accept it before being able to talk to them.
This is done using the new_chat_created event found in the readme.

**Comment by ghost** [comment]
HI!
For all future developers, who ask about this problem - solution next:
Привет для всех будущих разработчиков, кто задаст вопрос об этой проблеме - решение следующее:
```py
import asyncio

from telethon import TelegramClient
from telethon_secret_chat import SecretChatManager

client = TelegramClient("19522955612", api_id, api_hash, device_model="Xiaomi MI A1",
                                system_version="5.10.0", app_version="10 P (27)")
client.start()




async def send( chat,created_by_me):
    await manager.send_secret_message(chat, 'ну че пошли пить пивас?)))', parse_mode='html')

manager = SecretChatManager(client, auto_accept=True,
                            new_chat_created=send)  # automatically accept new secret chats
asyncio.get_event_loop().run_until_complete(manager.start_secret_chat("@username"))
with client:
    client.run_until_disconnected()```
